### ISSUE TITLE
TypeError: sub() got an unexpected keyword argument 'flags'

### ISSUE THREAD

**Issue by VikoTse** [mwhite/resume#34] opened 2015-07-26 14:44 UTC
When I "make", this Error appears as follows:

$ make
m -f *.html *.pdf
git submodule update --init
Submodule 'pandoc-templates' (https://github.com/mwhite/pandoc-templates.git) registered for path 'pandoc-templates'
Initialized empty Git repository in /home/vikotse/app/resume-master/resume/pandoc-templates/.git/
remote: Counting objects: 431, done.
remote: Total 431 (delta 0), reused 0 (delta 0), pack-reused 431
Receiving objects: 100% (431/431), 81.61 KiB | 27 KiB/s, done.
Resolving deltas: 100% (245/245), done.
Submodule path 'pandoc-templates': checked out '5fa97aeee84187e56533e0c6e925bc2d490ec4e7'
python resume.py tex < resume.md | pandoc  --template=./pandoc-templates/default.latex -H header.tex -o resume.pdf
/bin/sh: pandoc: command not found
Traceback (most recent call last):
  File "resume.py", line 172, in <module>
    main()
  File "resume.py", line 169, in main
    print(processor.process(format, lines, contact_lines, *sys.argv[1:]))
  File "resume.py", line 63, in process
    return handler(lines, contact_lines, *args)
  File "resume.py", line 108, in tex
    contact_lines = sub(search, replace[search], contact_lines)
  File "resume.py", line 88, in sub
    flags=flags, **kwargs)
TypeError: sub() got an unexpected keyword argument 'flags'
make: *** [resume.pdf] error 127

**Comment by mwhite** [comment] 2015-07-28 16:10
Duplicate of #17.  I would recommend installing Python 2.7.

**Closed by mwhite** 2015-07-28 16:10 UTC
